version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: com.android.application
        update-types: [version-update:semver-major]
      - dependency-name: com.android.library
        update-types: [version-update:semver-major]
      - dependency-name: gradle-wrapper
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
